In [ ]:
import pandas as pd
from tqdm import tqdm

from src.models.llm_call_helpers import *

:

# Load data

Load the videos of interest = videos around declines for each channel. Each video comes with its channel, upload week, title and description.

In [17]:
videos = pd.read_csv('data/bb_videos_title_around_declines1.csv', index_col=(0))

videos = videos.reset_index(drop=True)

videos

,channel_id,week,title
0,UCzVw9odnihM5PgKSv5UnDPA,247,Most Funny Babies and Kids Playing in Water - ...
1,UCzVw9odnihM5PgKSv5UnDPA,246,Kids and Babies Trying to do Exercises Funny...
2,UCzVw9odnihM5PgKSv5UnDPA,246,Cute and Adorable Moments of kids meeting newb...
3,UCzVw9odnihM5PgKSv5UnDPA,245,Cute Baby and His Daughter playing and Laughing
4,UCzVw9odnihM5PgKSv5UnDPA,244,Kids and Babies Meeting Animals in Village and...
...,...,...,...
107612,UCs06q9pyRn8d8xy0NgzKPrA,216,Tay K Allegedly Started a new gang in Jail cal...
107613,UCs06q9pyRn8d8xy0NgzKPrA,216,YNW Melly being investigated for a THIRD Murde...
107614,UCs06q9pyRn8d8xy0NgzKPrA,215,Face To Face: Lil Reese x DJ Akademiks: Talks ...
107615,UCrwmu-gceGOmtZeuTsn7DlQ,193,The Black Eyed Peas - BIG LOVE
107616,UCrwmu-gceGOmtZeuTsn7DlQ,175,The Black Eyed Peas - RING THE ALARM pt.1 pt.2...

# Apply LLM functions

For each video, apply the LLM functions to extract the following features:
- whether the video is an apology video
- whether the video addresses the decline
- whether the video announces a comeback
- whether the video announces a break
- whether the video is a collaboration video
- whether the video is a clickbait video

In [18]:
# apply the LLM model to the videos
tqdm.pandas()

videos['decline_addressed'] = videos['title'].progress_apply(lambda x: address_decline(x))

 41%|████      | 44044/107617 [4:16:57<5:40:07,  3.12it/s]

In [ ]:
videos

,channel_id,week,title,apology
0,UCzVw9odnihM5PgKSv5UnDPA,247,Most Funny Babies and Kids Playing in Water - ...,False
1,UCzVw9odnihM5PgKSv5UnDPA,246,Kids and Babies Trying to do Exercises Funny...,False
2,UCzVw9odnihM5PgKSv5UnDPA,246,Cute and Adorable Moments of kids meeting newb...,False
3,UCzVw9odnihM5PgKSv5UnDPA,245,Cute Baby and His Daughter playing and Laughing,False
4,UCzVw9odnihM5PgKSv5UnDPA,244,Kids and Babies Meeting Animals in Village and...,False
...,...,...,...,...
107612,UCs06q9pyRn8d8xy0NgzKPrA,216,Tay K Allegedly Started a new gang in Jail cal...,False
107613,UCs06q9pyRn8d8xy0NgzKPrA,216,YNW Melly being investigated for a THIRD Murde...,False
107614,UCs06q9pyRn8d8xy0NgzKPrA,215,Face To Face: Lil Reese x DJ Akademiks: Talks ...,False
107615,UCrwmu-gceGOmtZeuTsn7DlQ,193,The Black Eyed Peas - BIG LOVE,False
107616,UCrwmu-gceGOmtZeuTsn7DlQ,175,The Black Eyed Peas - RING THE ALARM pt.1 pt.2...,False

In [ ]:
videos['decline_addressed'].value_counts()

apology
False    107419
True        198
Name: count, dtype: int64

In [ ]:
# print the index of the videos that are apologies
apologies = videos[videos['decline_addressed'] == 'True']
apologies

,channel_id,week,title,apology
157,UCzUV5283-l5c0oKRtyenj6Q,231,I Guess We Were Wrong,True
991,UCzE4rHZD7TdxGqfMzVT_p2w,212,I'm going to regret this...,True
1036,UCzE4rHZD7TdxGqfMzVT_p2w,169,I LET MYSELF DOWN,True
1463,UCrqsNpKuDQZreGaxBL_a5Jg,232,i cant do this anymore,True
1659,UCrqsNpKuDQZreGaxBL_a5Jg,130,If You Watch This Video Please Dont Judge Me,True
...,...,...,...,...
106905,UCsDmESjqNPukDmVnuneLrqw,220,I can't do this anymore,True
107362,UCs3l6DsCu9ZOXkJkvskEsrQ,120,I MADE A MISTAKE...,True
107529,UCs11Yv5OnpY_b3Bff5ZJ9kw,184,i need help..,True
107555,UCs06q9pyRn8d8xy0NgzKPrA,240,Kodak Black apologizes and Squashes Beef with ...,True
107595,UCs06q9pyRn8d8xy0NgzKPrA,222,Kodak Black apologizes for Nipsey Hussle/Laure...,True

In [ ]:
# Basic stats on the featuring
print('Number of declines addressed:', len(apologies))
print('Number of videos:', len(videos))
print('Percentage of declines addressed:', len(apologies) / len(videos))

Number of apologies: 198
Number of videos: 107617
Percentage of apologies: 0.0018398580149976305

In [ ]:
videos.to_csv('data/bb_videos_decline_addressed.csv')